[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Updated image optimization settings with less aggressive caching
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Content Security Policy
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = '''
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval';
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' data: https: blob:;
      connect-src 'self' https://api.openai.com https://corsproxy.io https://api.allorigins.win https://api.codetabs.com https://cors-anywhere.herokuapp.com https://www.theguardian.com;
      frame-src 'none';
      object-src 'none';
      base-uri 'self';
      form-action 'self';
    '''

# Redirect rules
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Image optimization redirects for WebP support
[[redirects]]
  from = "/*.jpg"
  to = "/*.webp"
  status = 200
  conditions = {Accept = "image/webp"}

[[redirects]]
  from = "/*.jpeg"
  to = "/*.webp"
  status = 200
  conditions = {Accept = "image/webp"}

[[redirects]]
  from = "/*.png"
  to = "/*.webp"
  status = 200
  conditions = {Accept = "image/webp"}

# Functions configuration
[functions]
  directory = "netlify/functions"
  
[functions."generate-poem"]
  timeout = 30

[functions."generate-anchors"]
  timeout = 15

[functions."transform-headline"]
  timeout = 15

[functions."validate-poem"]
  timeout = 15